import type { Locale } from "@/lib/i18n"

export interface Project {
  name: string
  description: string
  achievements: string[]
}

export interface Experience {
  title: string
  company: string
  period: string
  location: string
  type: string
  description: string
  projects?: Project[]
  achievements?: string[]
  technologies: string[]
  bgColor: string
  borderColor: string
  textColor: string
}

export const experiences: Record<Locale, Experience[]> = {
  en: [
    {
      title: "Frontend Developer and Accessibility Engineer",
      company: "Freelance",
      period: "Sep 2024 - Present",
      location: "Remote",
      type: "Freelance",
      description:
        "Working as a freelance developer and accessibility consultant for high-profile brands and startups. Focus on delivering performant, inclusive, and scalable solutions using modern web technologies and collaborating with global teams.",
      projects: [
        {
          name: "Nespresso",
          description:
            "Global team implementing accessibility improvements and frontend features for 28+ international markets",
          achievements: [
            "Implemented accessibility improvements and frontend features for 28+ international markets",
            "Contributed to Drupal migrations and marketing campaign components",
            "Developed accessible components using React, TypeScript, HTML/CSS, Vanilla JS",
            "Participated in design planning and stakeholder discussions",
            "Conducted audits with axe, VoiceOver, keyboard navigation using Storybook and SCRUM",
          ],
        },
        {
          name: "Harley Davidson",
          description: "Enhanced accessibility on brand's homepage with agency collaboration",
          achievements: [
            "Enhanced accessibility on brand's homepage, including overlays, modals, and navigation",
            "Built components using Next.js, TypeScript, Tailwind CSS, Contentful",
            "Applied accessible interaction patterns using Storybook and WCAG principles",
            "Contributed to a microfrontend architecture",
          ],
        },
        {
          name: "BiomeMakers",
          description: "Built internal dashboards and generated printable PDFs for agricultural analytics",
          achievements: [
            "Built internal dashboards and generated printable PDFs for agricultural analytics",
            "Developed UI with Nunjucks, Vanilla JS, HTML, CSS",
            "Created components like cards, tables, and data visualization modules",
            "Maintained direct client communication and delivery management",
          ],
        },
        {
          name: "Supra",
          description:
            "Designed and deployed company's full website from scratch for construction/engineering services",
          achievements: [
            "Designed and deployed company's full website from scratch for construction/engineering services",
            "Used Next.js, TypeScript, Tailwind CSS, Contentful",
            "Architected site structure and deployed on Vercel with responsive and SEO-ready pages",
          ],
        },
      ],
      technologies: [
        "React",
        "Next.js",
        "TypeScript",
        "Tailwind CSS",
        "Contentful",
        "Storybook",
        "WCAG",
        "Axe",
        "VoiceOver",
        "Nunjucks",
        "Vanilla JS",
        "Drupal",
      ],
      bgColor: "bg-lavender-100",
      borderColor: "border-lavender-300",
      textColor: "text-lavender-800",
    },
    {
      title: "Software Engineer",
      company: "SmartAsset",
      period: "Jan 2024 - Oct 2024",
      location: "Buenos Aires, Argentina (Remote)",
      type: "Full-time",
      description:
        "Led the migration of blog and dashboard from legacy architecture to modern tech stack at a fintech platform supporting investors. Focused on improving SEO, performance, and maintainability through server-side rendering and clean, scalable components, resulting in higher user engagement and increased revenue.",
      achievements: [
        "Migrated legacy systems to Next.js, React, TypeScript, GraphQL, PHP, and WordPress",
        "Optimized Core Web Vitals and SEO with SSR results tracked via Mixpanel",
        "Built features such as filters, pagination, forms, modals, and content tools",
        "Integrated Optimizely SSR for A/B testing and user segmentation",
        "Enhanced accessibility and Lighthouse performance scores significantly",
        "Collaborated daily with design, QA, and product teams in Agile/SCRUM environment",
      ],
      technologies: [
        "Next.js",
        "React",
        "TypeScript",
        "GraphQL",
        "PHP",
        "WordPress",
        "Optimizely",
        "Mixpanel",
        "Lighthouse",
      ],
      bgColor: "bg-sky-100",
      borderColor: "border-sky-300",
      textColor: "text-sky-800",
    },
    {
      title: "Frontend Developer",
      company: "Ceres Imaging",
      period: "Jan 2023 - Aug 2023",
      location: "Buenos Aires, Argentina (Remote)",
      type: "Full-time",
      description:
        "Developed dashboards and geospatial tools for agricultural analytics platform supporting growers across North America, Europe, and South America. Played a key role in technical migration while maintaining legacy tools and improving usability and performance.",
      achievements: [
        "Migrated internal dashboards from Django to Next.js + GraphQL architecture",
        "Built UI features including filters (Vue/Vuex/Vuetify), tables (MUI), and map layers (Mapbox)",
        "Fixed critical geolocation bugs, improving stability and accuracy significantly",
        "Enhanced frontend performance and UI responsiveness across the platform",
        "Used Vue.js, React, Recoil, JavaScript, GraphQL, Vercel, and GitHub",
        "Collaborated with backend, design, and product teams in Agile SCRUM environment",
      ],
      technologies: ["Vue.js", "React", "Next.js", "GraphQL", "Recoil", "Vuetify", "Material UI", "Mapbox", "Vercel"],
      bgColor: "bg-mint-100",
      borderColor: "border-mint-300",
      textColor: "text-mint-800",
    },
    {
      title: "Frontend Developer and Accessibility Engineer",
      company: "Indeed",
      period: "Sep 2021 - Jan 2023",
      location: "Buenos Aires, Argentina",
      type: "Full-time",
      description:
        "Worked on multiple consumer-facing platforms and internal tools with a strong focus on accessibility, scalability, and design systems. Had a leadership role in accessibility improvements and testing practices.",
      achievements: [
        "Built reusable, accessible components with React, TypeScript, Redux, Emotion, Sass",
        "Increased test coverage to 85% by migrating unit tests to React Testing Library (RTL)",
        "Implemented custom focus management for keyboard users to resolve navigation loss",
        "Refactored legacy code, upgraded components using Storybook",
        "Ensured compliance with WCAG 2.1 AA and ARIA roles",
        "Collaborated with QA, UX, and tech leads to deliver accessible user flows",
        "Used Cypress, Enzyme, SCRUM, Jira, and Agile processes",
      ],
      technologies: [
        "React",
        "TypeScript",
        "Redux",
        "Emotion",
        "Sass",
        "React Testing Library",
        "Storybook",
        "Cypress",
        "Enzyme",
        "WCAG 2.1 AA",
        "ARIA",
      ],
      bgColor: "bg-rose-100",
      borderColor: "border-rose-300",
      textColor: "text-rose-800",
    },
    {
      title: "Frontend Developer",
      company: "Telecom Argentina",
      period: "Nov 2020 - Sep 2021",
      location: "Buenos Aires, Argentina",
      type: "Full-time",
      description:
        "Contributed to the development of the Flow Smart TV app, focusing on both legacy maintenance and migration to a modern frontend stack. Addressed major performance and stability issues during high-traffic events.",
      achievements: [
        "Maintained legacy code with React, Redux, Vanilla JS",
        "Migrated app to Next.js, TypeScript, React Context, RTL",
        "Developed custom spatial navigation systems for Smart TV interaction",
        "Built an accessible queue system to prevent crashes during traffic spikes",
        "Developed a video player and state management for the new architecture",
        "Participated in discussions on building a future monorepo strategy",
        "Used Tailwind, Storybook, and testing tools",
      ],
      technologies: [
        "React",
        "Next.js",
        "TypeScript",
        "Redux",
        "React Context",
        "Tailwind CSS",
        "Storybook",
        "Vanilla JS",
      ],
      bgColor: "bg-sunshine-100",
      borderColor: "border-sunshine-300",
      textColor: "text-sunshine-800",
    },
    {
      title: "Accessibility Analyst",
      company: "eSSENTIAL Accessibility",
      period: "Dec 2019 - Aug 2020",
      location: "Buenos Aires, Argentina",
      type: "Full-time",
      description:
        "Provided technical audits and consulting for global brands in finance, retail, and food industries. Role combined hands-on remediation, client communication, and team mentoring.",
      achievements: [
        "Audited sites using axe, NVDA, JAWS, VoiceOver, and keyboard navigation",
        "Conducted evaluations under WCAG 2.1 AA standards",
        "Fixed accessibility issues using HTML, CSS, JavaScript, React",
        "Delivered accessibility reports and action plans to clients",
        "Mentored and trained junior accessibility testers",
        "Collaborated in SCRUM teams across technical and non-technical stakeholders",
      ],
      technologies: ["WCAG 2.1 AA", "Axe", "NVDA", "JAWS", "VoiceOver", "HTML", "CSS", "JavaScript", "React"],
      bgColor: "bg-peach-100",
      borderColor: "border-peach-300",
      textColor: "text-peach-800",
    },
    {
      title: "Software Engineer",
      company: "Accenture Argentina",
      period: "Jun 2019 - Dec 2019",
      location: "Argentina",
      type: "Full-time",
      description:
        "Developed responsive web interfaces and improved accessibility in enterprise applications using modern web technologies and cloud services.",
      achievements: [
        "Developed native website using Vue.js, JavaScript, HTML/CSS",
        "Implemented responsive design principles and improved accessibility",
        "Used AWS and Node.js for backend integration and cloud deployment",
        "Refactored UI components for better accessibility and responsiveness",
        "Focused on performance optimization and user experience improvements",
      ],
      technologies: ["Vue.js", "JavaScript", "HTML/CSS", "AWS", "Node.js", "Responsive Design"],
      bgColor: "bg-cream-100",
      borderColor: "border-cream-300",
      textColor: "text-cream-800",
    },
  ],
  es: [
    {
      title: "Desarrollador Frontend e Ingeniera de Accesibilidad",
      company: "Freelance",
      period: "Sep 2024 - Presente",
      location: "Remoto",
      type: "Freelance",
      description:
        "Trabajando como desarrollador freelance e ingeniera de accesibilidad para marcas de alto perfil y startups. Enfoque en entregar soluciones eficientes, inclusivas y escalables usando tecnologías web modernas y colaborando con equipos globales.",
      projects: [
        {
          name: "Nespresso",
          description:
            "Equipo global implementando mejoras de accesibilidad y características frontend para 28+ mercados internacionales",
          achievements: [
            "Implementé mejoras de accesibilidad y características frontend para 28+ mercados internacionales",
            "Contribuí a migraciones de Drupal y componentes de campañas de marketing",
            "Desarrollé componentes accesibles usando React, TypeScript, HTML/CSS, Vanilla JS",
            "Participé en planificación de diseño y discusiones con stakeholders",
            "Realicé auditorías con axe, VoiceOver, navegación por teclado usando Storybook y SCRUM",
          ],
        },
        {
          name: "Harley Davidson",
          description: "Mejoré la accesibilidad en la página principal de la marca con colaboración de agencia",
          achievements: [
            "Mejoré la accesibilidad en la página principal de la marca, incluyendo overlays, modales y navegación",
            "Construí componentes usando Next.js, TypeScript, Tailwind CSS, Contentful",
            "Apliqué patrones de interacción accesibles usando Storybook y principios WCAG",
            "Contribuí a una arquitectura de microfrontend",
          ],
        },
        {
          name: "BiomeMakers",
          description: "Construí dashboards internos y generé PDFs imprimibles para análisis agrícolas",
          achievements: [
            "Construí dashboards internos y generé PDFs imprimibles para análisis agrícolas",
            "Desarrollé UI con Nunjucks, Vanilla JS, HTML, CSS",
            "Creé componentes como tarjetas, tablas y módulos de visualización de datos",
            "Mantuve comunicación directa con clientes y gestión de entregas",
          ],
        },
        {
          name: "Supra",
          description:
            "Diseñé y desplegué el sitio web completo de la empresa desde cero para servicios de construcción/ingeniería",
          achievements: [
            "Diseñé y desplegué el sitio web completo de la empresa desde cero para servicios de construcción/ingeniería",
            "Usé Next.js, TypeScript, Tailwind CSS, Contentful",
            "Arquitecturé la estructura del sitio y desplegué en Vercel con páginas responsivas y listas para SEO",
          ],
        },
      ],
      technologies: [
        "React",
        "Next.js",
        "TypeScript",
        "Tailwind CSS",
        "Contentful",
        "Storybook",
        "WCAG",
        "Axe",
        "VoiceOver",
        "Nunjucks",
        "Vanilla JS",
        "Drupal",
      ],
      bgColor: "bg-lavender-100",
      borderColor: "border-lavender-300",
      textColor: "text-lavender-800",
    },
    {
      title: "Ingeniero de Software",
      company: "SmartAsset",
      period: "Ene 2024 - Oct 2024",
      location: "Buenos Aires, Argentina (Remoto)",
      type: "Tiempo Completo",
      description:
        "Lideré la migración del blog y dashboard desde arquitectura legacy a stack tecnológico moderno en una plataforma fintech que apoya inversores. Enfoque en mejorar SEO, rendimiento y mantenibilidad a través de renderizado del lado del servidor y componentes limpios y escalables, resultando en mayor engagement de usuarios e ingresos incrementados.",
      achievements: [
        "Migré sistemas legacy a Next.js, React, TypeScript, GraphQL, PHP y WordPress",
        "Optimicé Core Web Vitals y SEO con SSR resultados rastreados vía Mixpanel",
        "Construí características como filtros, paginación, formularios, modales y herramientas de contenido",
        "Integré Optimizely SSR para pruebas A/B y segmentación de usuarios",
        "Mejoré significativamente las puntuaciones de accesibilidad y rendimiento de Lighthouse",
        "Colaboré diariamente con equipos de diseño, QA y producto en ambiente Agile/SCRUM",
      ],
      technologies: [
        "Next.js",
        "React",
        "TypeScript",
        "GraphQL",
        "PHP",
        "WordPress",
        "Optimizely",
        "Mixpanel",
        "Lighthouse",
      ],
      bgColor: "bg-sky-100",
      borderColor: "border-sky-300",
      textColor: "text-sky-800",
    },
    {
      title: "Desarrollador Frontend",
      company: "Ceres Imaging",
      period: "Ene 2023 - Ago 2023",
      location: "Buenos Aires, Argentina (Remoto)",
      type: "Tiempo Completo",
      description:
        "Desarrollé dashboards y herramientas geoespaciales para plataforma de análisis agrícola que apoya cultivadores en América del Norte, Europa y América del Sur. Jugué un papel clave en la migración técnica mientras mantenía herramientas legacy y mejoraba usabilidad y rendimiento.",
      achievements: [
        "Migré dashboards internos de Django a arquitectura Next.js + GraphQL",
        "Construí características de UI incluyendo filtros (Vue/Vuex/Vuetify), tablas (MUI) y capas de mapas (Mapbox)",
        "Arreglé bugs críticos de geolocalización, mejorando significativamente estabilidad y precisión",
        "Mejoré el rendimiento frontend y la capacidad de respuesta de la UI en toda la plataforma",
        "Usé Vue.js, React, Recoil, JavaScript, GraphQL, Vercel y GitHub",
        "Colaboré con equipos de backend, diseño y producto en ambiente Agile SCRUM",
      ],
      technologies: ["Vue.js", "React", "Next.js", "GraphQL", "Recoil", "Vuetify", "Material UI", "Mapbox", "Vercel"],
      bgColor: "bg-mint-100",
      borderColor: "border-mint-300",
      textColor: "text-mint-800",
    },
    {
      title: "Desarrollador Frontend y Ingeniera de Accesibilidad",
      company: "Indeed",
      period: "Sep 2021 - Ene 2023",
      location: "Buenos Aires, Argentina",
      type: "Tiempo Completo",
      description:
        "Trabajé en múltiples plataformas orientadas al consumidor y herramientas internas con un fuerte enfoque en accesibilidad, escalabilidad y sistemas de diseño. Tuve un rol de liderazgo en mejoras de accesibilidad y prácticas de testing.",
      achievements: [
        "Construí componentes reutilizables y accesibles con React, TypeScript, Redux, Emotion, Sass",
        "Aumenté la cobertura de tests al 85% migrando unit tests a React Testing Library (RTL)",
        "Implementé manejo personalizado de focus para usuarios de teclado para resolver pérdida de navegación",
        "Refactoricé código legacy, actualicé componentes usando Storybook",
        "Aseguré cumplimiento con WCAG 2.1 AA y roles ARIA",
        "Colaboré con QA, UX y tech leads para entregar flujos de usuario accesibles",
        "Usé Cypress, Enzyme, SCRUM, Jira y procesos Agile",
      ],
      technologies: [
        "React",
        "TypeScript",
        "Redux",
        "Emotion",
        "Sass",
        "React Testing Library",
        "Storybook",
        "Cypress",
        "Enzyme",
        "WCAG 2.1 AA",
        "ARIA",
      ],
      bgColor: "bg-rose-100",
      borderColor: "border-rose-300",
      textColor: "text-rose-800",
    },
    {
      title: "Desarrollador Frontend",
      company: "Telecom Argentina",
      period: "Nov 2020 - Sep 2021",
      location: "Buenos Aires, Argentina",
      type: "Tiempo Completo",
      description:
        "Contribuí al desarrollo de la app Flow Smart TV, enfocándome tanto en mantenimiento legacy como en migración a un stack frontend moderno. Abordé problemas importantes de rendimiento y estabilidad durante eventos de alto tráfico.",
      achievements: [
        "Mantuve código legacy con React, Redux, Vanilla JS",
        "Migré app a Next.js, TypeScript, React Context, RTL",
        "Desarrollé sistemas de navegación espacial personalizados para interacción Smart TV",
        "Construí un sistema de cola accesible para prevenir crashes durante picos de tráfico",
        "Desarrollé un reproductor de video y manejo de estado para la nueva arquitectura",
        "Participé en discusiones sobre construcción de estrategia futura de monorepo",
        "Usé Tailwind, Storybook y herramientas de testing",
      ],
      technologies: [
        "React",
        "Next.js",
        "TypeScript",
        "Redux",
        "React Context",
        "Tailwind CSS",
        "Storybook",
        "Vanilla JS",
      ],
      bgColor: "bg-sunshine-100",
      borderColor: "border-sunshine-300",
      textColor: "text-sunshine-800",
    },
    {
      title: "Analista de Accesibilidad",
      company: "eSSENTIAL Accessibility",
      period: "Dic 2019 - Ago 2020",
      location: "Buenos Aires, Argentina",
      type: "Tiempo Completo",
      description:
        "Proporcioné auditorías técnicas y consultoría para marcas globales en industrias de finanzas, retail y alimentación. El rol combinó remediación práctica, comunicación con clientes y mentoría de equipo.",
      achievements: [
        "Audité sitios usando axe, NVDA, JAWS, VoiceOver y navegación por teclado",
        "Realicé evaluaciones bajo estándares WCAG 2.1 AA",
        "Arreglé problemas de accesibilidad usando HTML, CSS, JavaScript, React",
        "Entregué reportes de accesibilidad y planes de acción a clientes",
        "Mentoré y entrené testers junior de accesibilidad",
        "Colaboré en equipos SCRUM a través de stakeholders técnicos y no técnicos",
      ],
      technologies: ["WCAG 2.1 AA", "Axe", "NVDA", "JAWS", "VoiceOver", "HTML", "CSS", "JavaScript", "React"],
      bgColor: "bg-peach-100",
      borderColor: "border-peach-300",
      textColor: "text-peach-800",
    },
    {
      title: "Ingeniero de Software",
      company: "Accenture Argentina",
      period: "Jun 2019 - Dic 2019",
      location: "Argentina",
      type: "Tiempo Completo",
      description:
        "Desarrollé interfaces web responsivas y mejoré la accesibilidad en aplicaciones empresariales usando tecnologías web modernas y servicios en la nube.",
      achievements: [
        "Desarrollé sitio web nativo usando Vue.js, JavaScript, HTML/CSS",
        "Implementé principios de diseño responsivo y mejoré la accesibilidad",
        "Usé AWS y Node.js para integración backend y despliegue en la nube",
        "Refactoricé componentes UI para mejor accesibilidad y capacidad de respuesta",
        "Me enfoqué en optimización de rendimiento y mejoras de experiencia de usuario",
      ],
      technologies: ["Vue.js", "JavaScript", "HTML/CSS", "AWS", "Node.js", "Diseño Responsivo"],
      bgColor: "bg-cream-100",
      borderColor: "border-cream-300",
      textColor: "text-cream-800",
    },
  ],
  it: [
    {
      title: "Sviluppatore Frontend e Ingegnere di Accessibilità",
      company: "Freelance",
      period: "Set 2024 - Presente",
      location: "Remoto",
      type: "Freelance",
      description:
        "Lavoro come sviluppatore freelance e ingegnere di accessibilità per marchi di alto profilo e startup. Focus sulla consegna di soluzioni performanti, inclusive e scalabili utilizzando tecnologie web moderne e collaborando con team globali.",
      projects: [
        {
          name: "Nespresso",
          description:
            "Team globale che implementa miglioramenti di accessibilità e funzionalità frontend per 28+ mercati internazionali",
          achievements: [
            "Implementato miglioramenti di accessibilità e funzionalità frontend per 28+ mercati internazionali",
            "Contribuito alle migrazioni Drupal e componenti di campagne marketing",
            "Sviluppato componenti accessibili usando React, TypeScript, HTML/CSS, Vanilla JS",
            "Partecipato alla pianificazione del design e discussioni con stakeholder",
            "Condotto audit con axe, VoiceOver, navigazione da tastiera usando Storybook e SCRUM",
          ],
        },
        {
          name: "Harley Davidson",
          description: "Migliorato l'accessibilità sulla homepage del brand con collaborazione di agenzia",
          achievements: [
            "Migliorato l'accessibilità sulla homepage del brand, inclusi overlay, modal e navigazione",
            "Costruito componenti usando Next.js, TypeScript, Tailwind CSS, Contentful",
            "Applicato pattern di interazione accessibili usando Storybook e principi WCAG",
            "Contribuito a un'architettura microfrontend",
          ],
        },
        {
          name: "BiomeMakers",
          description: "Costruito dashboard interni e generato PDF stampabili per analisi agricole",
          achievements: [
            "Costruito dashboard interni e generato PDF stampabili per analisi agricole",
            "Sviluppato UI con Nunjucks, Vanilla JS, HTML, CSS",
            "Creato componenti come card, tabelle e moduli di visualizzazione dati",
            "Mantenuto comunicazione diretta con clienti e gestione delle consegne",
          ],
        },
        {
          name: "Supra",
          description:
            "Progettato e distribuito il sito web completo dell'azienda da zero per servizi di costruzione/ingegneria",
          achievements: [
            "Progettato e distribuito il sito web completo dell'azienda da zero per servizi di costruzione/ingegneria",
            "Utilizzato Next.js, TypeScript, Tailwind CSS, Contentful",
            "Architettato la struttura del sito e distribuito su Vercel con pagine responsive e pronte per SEO",
          ],
        },
      ],
      technologies: [
        "React",
        "Next.js",
        "TypeScript",
        "Tailwind CSS",
        "Contentful",
        "Storybook",
        "WCAG",
        "Axe",
        "VoiceOver",
        "Nunjucks",
        "Vanilla JS",
        "Drupal",
      ],
      bgColor: "bg-lavender-100",
      borderColor: "border-lavender-300",
      textColor: "text-lavender-800",
    },
    {
      title: "Ingegnere Software",
      company: "SmartAsset",
      period: "Gen 2024 - Ott 2024",
      location: "Buenos Aires, Argentina (Remoto)",
      type: "Tempo Pieno",
      description:
        "Guidato la migrazione di blog e dashboard da architettura legacy a stack tecnologico moderno in una piattaforma fintech che supporta investitori. Focus sul miglioramento di SEO, performance e manutenibilità attraverso rendering lato server e componenti puliti e scalabili, risultando in maggiore coinvolgimento degli utenti e aumento dei ricavi.",
      achievements: [
        "Migrato sistemi legacy a Next.js, React, TypeScript, GraphQL, PHP e WordPress",
        "Ottimizzato Core Web Vitals e SEO con SSR risultati tracciati via Mixpanel",
        "Costruito funzionalità come filtri, paginazione, form, modal e strumenti di contenuto",
        "Integrato Optimizely SSR per test A/B e segmentazione utenti",
        "Migliorato significativamente i punteggi di accessibilità e performance di Lighthouse",
        "Collaborato quotidianamente con team di design, QA e prodotto in ambiente Agile/SCRUM",
      ],
      technologies: [
        "Next.js",
        "React",
        "TypeScript",
        "GraphQL",
        "PHP",
        "WordPress",
        "Optimizely",
        "Mixpanel",
        "Lighthouse",
      ],
      bgColor: "bg-sky-100",
      borderColor: "border-sky-300",
      textColor: "text-sky-800",
    },
    {
      title: "Sviluppatore Frontend",
      company: "Ceres Imaging",
      period: "Gen 2023 - Ago 2023",
      location: "Buenos Aires, Argentina (Remoto)",
      type: "Tempo Pieno",
      description:
        "Sviluppato dashboard e strumenti geospaziali per piattaforma di analisi agricola che supporta coltivatori in Nord America, Europa e Sud America. Giocato un ruolo chiave nella migrazione tecnica mantenendo strumenti legacy e migliorando usabilità e performance.",
      achievements: [
        "Migrato dashboard interni da Django a architettura Next.js + GraphQL",
        "Costruito funzionalità UI inclusi filtri (Vue/Vuex/Vuetify), tabelle (MUI) e layer mappe (Mapbox)",
        "Risolto bug critici di geolocalizzazione, migliorando significativamente stabilità e accuratezza",
        "Migliorato performance frontend e reattività UI attraverso la piattaforma",
        "Utilizzato Vue.js, React, Recoil, JavaScript, GraphQL, Vercel e GitHub",
        "Collaborato con team backend, design e prodotto in ambiente Agile SCRUM",
      ],
      technologies: ["Vue.js", "React", "Next.js", "GraphQL", "Recoil", "Vuetify", "Material UI", "Mapbox", "Vercel"],
      bgColor: "bg-mint-100",
      borderColor: "border-mint-300",
      textColor: "text-mint-800",
    },
    {
      title: "Sviluppatore Frontend e Ingegnere di Accessibilità",
      company: "Indeed",
      period: "Set 2021 - Gen 2023",
      location: "Buenos Aires, Argentina",
      type: "Tempo Pieno",
      description:
        "Lavorato su multiple piattaforme consumer-facing e strumenti interni con forte focus su accessibilità, scalabilità e design system. Avuto ruolo di leadership nei miglioramenti di accessibilità e pratiche di testing.",
      achievements: [
        "Costruito componenti riutilizzabili e accessibili con React, TypeScript, Redux, Emotion, Sass",
        "Aumentato copertura test all'85% migrando unit test a React Testing Library (RTL)",
        "Implementato gestione focus personalizzata per utenti tastiera per risolvere perdita navigazione",
        "Refactorizzato codice legacy, aggiornato componenti usando Storybook",
        "Assicurato conformità con WCAG 2.1 AA e ruoli ARIA",
        "Collaborato con QA, UX e tech lead per consegnare flussi utente accessibili",
        "Utilizzato Cypress, Enzyme, SCRUM, Jira e processi Agile",
      ],
      technologies: [
        "React",
        "TypeScript",
        "Redux",
        "Emotion",
        "Sass",
        "React Testing Library",
        "Storybook",
        "Cypress",
        "Enzyme",
        "WCAG 2.1 AA",
        "ARIA",
      ],
      bgColor: "bg-rose-100",
      borderColor: "border-rose-300",
      textColor: "text-rose-800",
    },
    {
      title: "Sviluppatore Frontend",
      company: "Telecom Argentina",
      period: "Nov 2020 - Set 2021",
      location: "Buenos Aires, Argentina",
      type: "Tempo Pieno",
      description:
        "Contribuito allo sviluppo dell'app Flow Smart TV, focalizzandomi sia su manutenzione legacy che migrazione a stack frontend moderno. Affrontato problemi importanti di performance e stabilità durante eventi ad alto traffico.",
      achievements: [
        "Mantenuto codice legacy con React, Redux, Vanilla JS",
        "Migrato app a Next.js, TypeScript, React Context, RTL",
        "Sviluppato sistemi di navigazione spaziale personalizzati per interazione Smart TV",
        "Costruito sistema di coda accessibile per prevenire crash durante picchi di traffico",
        "Sviluppato video player e gestione stato per nuova architettura",
        "Partecipato a discussioni su costruzione strategia futura monorepo",
        "Utilizzato Tailwind, Storybook e strumenti di testing",
      ],
      technologies: [
        "React",
        "Next.js",
        "TypeScript",
        "Redux",
        "React Context",
        "Tailwind CSS",
        "Storybook",
        "Vanilla JS",
      ],
      bgColor: "bg-sunshine-100",
      borderColor: "border-sunshine-300",
      textColor: "text-sunshine-800",
    },
    {
      title: "Analista di Accessibilità",
      company: "eSSENTIAL Accessibility",
      period: "Dic 2019 - Ago 2020",
      location: "Buenos Aires, Argentina",
      type: "Tempo Pieno",
      description:
        "Fornito audit tecnici e consulenza per brand globali in settori finanza, retail e alimentare. Il ruolo combinava rimedio pratico, comunicazione clienti e mentoring team.",
      achievements: [
        "Auditato siti usando axe, NVDA, JAWS, VoiceOver e navigazione tastiera",
        "Condotto valutazioni sotto standard WCAG 2.1 AA",
        "Risolto problemi di accessibilità usando HTML, CSS, JavaScript, React",
        "Consegnato report accessibilità e piani d'azione ai clienti",
        "Fatto mentoring e addestrato tester junior di accessibilità",
        "Collaborato in team SCRUM attraverso stakeholder tecnici e non tecnici",
      ],
      technologies: ["WCAG 2.1 AA", "Axe", "NVDA", "JAWS", "VoiceOver", "HTML", "CSS", "JavaScript", "React"],
      bgColor: "bg-peach-100",
      borderColor: "border-peach-300",
      textColor: "text-peach-800",
    },
    {
      title: "Ingegnere Software",
      company: "Accenture Argentina",
      period: "Giu 2019 - Dic 2019",
      location: "Argentina",
      type: "Tempo Pieno",
      description:
        "Sviluppato interfacce web responsive e migliorato accessibilità in applicazioni enterprise utilizzando tecnologie web moderne e servizi cloud.",
      achievements: [
        "Sviluppato sito web nativo usando Vue.js, JavaScript, HTML/CSS",
        "Implementato principi design responsive e migliorato accessibilità",
        "Utilizzato AWS e Node.js per integrazione backend e deployment cloud",
        "Refactorizzato componenti UI per migliore accessibilità e responsività",
        "Focalizzato su ottimizzazione performance e miglioramenti esperienza utente",
      ],
      technologies: ["Vue.js", "JavaScript", "HTML/CSS", "AWS", "Node.js", "Design Responsive"],
      bgColor: "bg-cream-100",
      borderColor: "border-cream-300",
      textColor: "text-cream-800",
    },
  ],
}

export const getExperienceData = (locale: Locale): Experience[] => {
  return experiences[locale] || experiences.en
}