# allow static assets and dev endpoints through (place BEFORE the catch-all)
[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200
  force = false

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200
  force = false

[[redirects]]
  from = "/og-image.png"
  to = "/og-image.png"
  status = 200
  force = false

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/src/*"
  to = "/src/:splat"
  status = 200
  force = false

# Vite dev endpoints (if you run netlify dev in local dev)
[[redirects]]
  from = "/@vite/*"
  to = "/@vite/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/@react-refresh/*"
  to = "/@react-refresh/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200